### ISSUE TITLE
bug: mpvc opens a new mpv window if idle=yes is used and nothing is currently player/queued

### ISSUE THREAD

**Issue by zombiehoffa** [gmt4/mpvc#2]
Hi,
if you set idle=yes in your mpv.conf file so mpv stays open but is not playing once it finishes the playlist mpvc opens a new window instead of completing the requested task in the open window (i.e add file opens a new mpv window and plays the file when mpvc should have added it to the existing window and played the file there.

**Comment by gmt4** [comment]
For an issue to be addressed, the issue must be reproducible, so a sequence of steps to reproduce the issue, and how the observed behavior differs from the expected behavior would be great, in absence of that it's difficult that gauge if this is an issue.

Anyway, to control an existing mpv instance via `mpvc`, first, `mpv` must be started with `mpv --input-ipc-socket=~/.config/mpvc/mpvsocket0`, once this is done it can be controlled with `mpvc --socket ~/.config/mpvc/mpvsocket0`. This is explained in https://github.com/gmt4/mpvc/#usage, so if you haven't, have a look, and try a couple of examples to make sure you understand them.

**Comment by zombiehoffa** [comment]
Yes, I am doing that with /tmp/mpvsocket as per that usage direction and the above is still happening (I assume you mean input-ipc-server= not input-ipc-socket for mpv?) I tried switching it over to my home dir as per above and still get the errors. My mpv.conf is as follows:

`#geometry=3850:0
#autofit=100%x63%
volume=50
video-sync=display-resample
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample
#for hyprland
geometry=50%
idle=yes
#gpu-context-wayland
input-ipc-server=~/.config/mpvc/mpvsocket0
#player-operation-mode=pseudo-gui
force-window=yes
terminal=no
`

when i start mpv manually with an mpv & from the cli I get no errors and the mpvsocket0 is created.
When I try to do an mpvc --socket ~/.config/mpvc/mpvsocket0 list I get:

MPV instance on /home/MYUSER/.config/mpvc/mpvsocket0 is currently idle.

When I try to add an random video file with:

mpvc --socket ~/.config/mpvc/mpvsocket0 add /mnt/syna/video/tv/Archer/Season\ 01/Archer\ \(2009\)\ -\ S01E10\ -\ Dial\ M\ for\ Mother\ HDTV-720p.mkv

I get:
MPV instance on /home/MYUSER/.config/mpvc/mpvsocket0 is currently idle.

When I try to add it with:

mpvc --socket ~/.config/mpvc/mpvsocket0 add /mnt/syna/video/tv/Archer/Season\ 01/Archer\ \(2009\)\ -\ S01E10\ -\ Dial\ M\ for\ Mother\ HDTV-720p.mkv

I get:
MPV instance on /home/MYUSER/.config/mpvc/mpvsocket0 is currently idle.

When I drag a file onto the open  but idle mpv window so that something is playing and then I try to list with:

mpvc --socket ~/.config/mpvc/mpvsocket0 list

I get: 

error - Carnival Row - S01E06 - Unaccompanied Fae WEBDL-720p Proper
[playing] #1/1 00:00:03/00:50:29 (0%)
speed: 1.00x volume: 50% muted: no repeat: no single: no


When I try to play a file with: 
mpvc --socket ~/.config/mpvc/mpvsocket0 play /mnt/syna/video/tv/Archer/Season\ 01/Archer\ \(2009\)\ -\ S01E10\ -\ Dial\ M\ for\ Mother\ HDTV-720p.mkv


I get:
error - Carnival Row - S01E06 - Unaccompanied Fae WEBDL-720p Proper
[playing] #1/1 00:00:46/00:50:29 (1%)
speed: 1.00x volume: 50% muted: no repeat: no single: no


I am not certain where this logs errors to or I would provide more in depth error than the above.

**Comment by gmt4** [comment]
I think I've now understood the issue. 

To start a mpvc controllable instance of mpv  you can  use `mpvc --mpv`, instead of setting  `input-ipc-server=~/.config/mpvc/mpvsocket0` in `mpv.conf` . 

In any case, I've pushed 5bec3286e64e573903ee4121fbfb15890f087703 that should also work when `idle=yes input-ipc-server=/path/to/socket` is set in `mpv.conf`

Can you update, check, and report back if the issue is solved in  5bec3286e64e573903ee4121fbfb15890f087703?

**Comment by zombiehoffa** [comment]
Thanks, I believe that fixed it.

**Comment by gmt4** [comment]
Great, Just a closing thought from: https://gmt4.github.io/mpvc/#gmt4-mpvc-fork

> "Star, share, and promote our work through the buttons below if you find it useful. Thanks!"
