### ISSUE TITLE
QuickInstall Error On Mac

### ISSUE THREAD

**Issue by tommedge** [gmt4/mpvc#5]
**Describe the Issue**
On Mac when running the Quick Install command it fails to fetch using curl. Tried with both system curl and homebrew curl

**To Reproduce**
`curl -fsSL -o mpvc-installer https://github.com/gmt4/mpvc/raw/master/extras/mpvc-installer && sh ./mpvc-installer fetch-user`

Gives 
```
Fetching mpvc from https://github.com/gmt4/mpvc
Fetch /Users/Tom.Edge/bin/mpvc-installer
curl: (3) URL rejected: Malformed input to a URL function
```

**Comment by gmt4** [comment]
Hi there, thanks for the report.

Bear in mind this is the first time I'm aware of anybody running mpvc on Mac.
This project is mostly focused on UNIX/Linux, mpvc has never been used/tested on mac before.

From the report, it seems that Mac default "sh" is behaving differently from the one in Linux. First, I'd recommend you using explicitly "bash" instead of "sh" to be sure, and if that fails, then run "bash -x" that will be more verbose for reporting the offending line.

You can find below the expected output of running "bash mpvc-installer fetch-user", so you get an idea of what to expect, actually is just fetching the scripts from the repo and making them executable, so you can also do this by hand, to test mpvc without using the without using the installer.

~~~
$ curl -fsSL -o mpvc-installer https://github.com/gmt4/mpvc/raw/master/extras/mpvc-installer
$ BINDIR=/tmp/mpvc-test/ bash ./mpvc-installer fetch-user

Fetching mpvc from https://github.com/gmt4/mpvc
Fetch /tmp/mpvc-test//mpvc from https://github.com/gmt4/mpvc/raw/master/mpvc
Fetch /tmp/mpvc-test//mpvc-tui from https://github.com/gmt4/mpvc/raw/master/extras/mpvc-tui
Fetch /tmp/mpvc-test//mpvc-fzf from https://github.com/gmt4/mpvc/raw/master/extras/mpvc-fzf
Fetch /tmp/mpvc-test//mpvc-cut from https://github.com/gmt4/mpvc/raw/master/extras/mpvc-cut
Fetch /tmp/mpvc-test//mpvc-chapter from https://github.com/gmt4/mpvc/raw/master/extras/mpvc-chapter
Fetch /tmp/mpvc-test//mpvc-mpris from https://github.com/gmt4/mpvc/raw/master/extras/mpvc-mpris
Fetch /tmp/mpvc-test//mpvc-equalizer from https://github.com/gmt4/mpvc/raw/master/extras/mpvc-equalizer
Fetch /tmp/mpvc-test//mpvc-web from https://github.com/gmt4/mpvc/raw/master/extras/mpvc-web
Fetch /tmp/mpvc-test//mpvc-autostart from https://github.com/gmt4/mpvc/raw/master/extras/mpvc-autostart
Fetch /tmp/mpvc-test//mpvc-installer from https://github.com/gmt4/mpvc/raw/master/extras/mpvc-installer
$
~~~

**Comment by gmt4** [comment]
For the record, next steps are covered in the FAQ:
https://github.com/gmt4/mpvc/wiki/FAQ#mac-support
